---
- name: Install Nagios on CentOS
  hosts: centos_nagios
  become: yes
  tasks:
    - name: Create Nagios user
      user:
        name: nagios

    - name: Create nagcmd group
      group:
        name: nagcmd

    - name: Add nagios to nagcmd group
      user:
        name: nagios
        groups: nagcmd
        append: yes

    - name: Add apache to nagcmd group
      user:
        name: apache
        groups: nagcmd
        append: yes

    - name: Create directory for Nagios installation
      file:
        path: ~/nagios
        state: directory

    - name: Change directory to Nagios installation directory
      command: cd ~/nagios

    - name: Download Nagios source
      get_url:
        url: https://prdownloads.sourceforge.net/projects/nagios/files/nagios-4.x/nagios-4.0.7/nagios-4.0.7.tar.gz
        dest: ~/nagios/nagios-4.0.7.tar.gz

    - name: Download Nagios Plugins source
      get_url:
        url: http://www.nagios-plugins.org/download/nagios-plugins-2.0.3.tar.gz
        dest: ~/nagios/nagios-plugins-2.0.3.tar.gz

    - name: Extract Nagios source
      command: tar zxvf ~/nagios/nagios-4.0.7.tar.gz
      args:
        chdir: ~/nagios

    - name: Extract Nagios Plugins source
      command: tar zxvf ~/nagios/nagios-plugins-2.0.3.tar.gz
      args:
        chdir: ~/nagios

    - name: Configure Nagios
      command: ./configure --with-command-group=nagcmd
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Compile Nagios
      command: make all
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios
      command: make install
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios init scripts
      command: make install-init
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios command mode
      command: make install-commandmode
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios config files
      command: make install-config
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios web component
      command: make install-webconf
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Set up nagiosadmin password
      command: htpasswd -s -c /usr/local/nagios/etc/htpasswd.users nagiosadmin

    - name: Restart Apache
      service:
        name: httpd
        state: restarted

    - name: Change directory to Nagios Plugins installation directory
      command: cd ~/nagios/nagios-plugins-2.0.3

    - name: Configure Nagios Plugins
      command: ./configure --with-nagios-user=nagios --with-nagios-group=nagios

    - name: Compile Nagios Plugins
      command: make

    - name: Install Nagios Plugins
      command: make install

    - name: Verify Nagios configuration
      command: /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg

    - name: Add Nagios to startup
      command: chkconfig --add nagios

    - name: Set Nagios to start on boot
      command: chkconfig --level 35 nagios on

    - name: Start Nagios service
      service:
        name: nagios
        state: started
