---
- name: Configure routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}
      register: config_output

    - name: Set enable secret
      ios_config:
        lines:
          - enable secret rdrgz
      register: config_output

    - name: Set console and vty passwords
      ios_config:
        lines:
          - line console 0
          - password rdrgz
          - login
          - line vty 0 4
          - password rdrgz
          - login
      register: config_output

    - name: Set banner
      ios_config:
        lines:
          - banner motd # Unauthorized Access Denied #
      register: config_output

    - name: Disable DNS lookup
      ios_config:
        lines:
          - no ip domain-lookup
      register: config_output
