---
- name: Nagios Installation and Configuration
  hosts: centos_nagios
  become: yes  # You might need to become a superuser for some tasks
  tasks:
    - name: Add nagios user
      user:
        name: nagios
        state: present

    - name: Add nagcmd group
      group:
        name: nagcmd
        state: present

    - name: Add nagios to nagcmd group
      user:
        name: nagios
        groups: nagcmd
        append: yes

    - name: Add apache to nagcmd group
      user:
        name: apache
        groups: nagcmd
        append: yes

    - name: Create Nagios directory PATH
      file:
        path: ~/nagios
        state: directory
        
    - name: Download Nagios Plugins
      get_url:
        url: http://www.nagios-plugins.org/download/nagios-plugins-2.0.3.tar.gz
        dest: ~/nagios/nagios-plugins.tar.gz
        mode: 0644

    - name: Extract Nagios Plugins
      shell: tar zxvf ~/nagios/nagios-plugins.tar.gz -C ~/nagios
      args:
        creates: ~/nagios/nagios-plugins-2.0.3

    - name: Configure Nagios
      command: >
        ./configure --with-command-group=nagcmd
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Compile and Install Nagios
      shell: |
        make all
        make install
        make install-init
        make install-commandmode
        make install-config
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Install Nagios Web Configuration
      shell: make install-webconf
      args:
        chdir: ~/nagios/nagios-4.0.7

    - name: Set up Nagios admin password
      command: >
        htpasswd -s -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
      ignore_errors: yes

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure Nagios Plugins
      command: >
        cd ~/nagios/nagios-plugins-2.0.3
        ./configure --with-nagios-user=nagios --with-nagios-group=nagios
      args:
        chdir: ~/nagios/nagios-plugins-2.0.3

    - name: Compile and Install Nagios Plugins
      shell: |
        cd ~/nagios/nagios-plugins-2.0.3
        make
        make install
      args:
        chdir: ~/nagios/nagios-plugins-2.0.3

    - name: Verify Nagios Configuration
      command: >
        /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
      changed_when: false

    - name: Add Nagios service to run at boot
      command: chkconfig --add nagios
      when: ansible_distribution_major_version == '7'

    - name: Set Nagios to run at boot
      command: chkconfig --level 35 nagios on
      when: ansible_distribution_major_version == '7'

    - name: Start Nagios service
      service:
        name: nagios
        state: started
      when: ansible_distribution_major_version == '7'
