---
- name: Configure Cisco routers
  hosts: routers
  gather_facts: no
  vars:
    ansible_user: gns3
    ansible_ssh_pass: gns3
    ansible_connection: network_cli
    ansible_network_os: ios
    enable_secret: enable_password_here
    line_vty_password: rdrgz

  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname R1

    - name: Set password
      ios_config:
        lines:
          - enable password rdrgz

    - name: Set enable secret
      ios_config:
        lines:
          - enable secret "{{ enable_secret }}"

    - name: Configure line vty
      ios_config:
        lines:
          - line vty 0 4
          - login
          - password "{{ line_vty_password }}"

    - name: Set banner
      ios_config:
        lines:
          - banner motd #Unauthorized Access Denied#

    - name: Disable IP domain lookup
      ios_config:
        lines:
          - no ip domain-lookup
