---
- name: Basic Cisco Router Configuration
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname Router
      register: result_hostname

    - name: Set enable secret
      ios_config:
        lines:
          - enable secret rdrgz

    - name: Set password
      ios_config:
        lines:
          - username ansible privilege 15 password 0 rdrgz

    - name: Configure line vty
      ios_config:
        lines:
          - line vty 0 4
          - login local

    - name: Set banner
      ios_config:
        lines:
          - banner motd ^Unauthorized Access Denied^

    - name: Disable IP domain lookup
      ios_config:
        lines:
          - no ip domain lookup
