---
- name: Nagios Installation and Configuration
  hosts: localhost
  become: yes  # You might need to become a superuser for some tasks
  tasks:
    - name: Install Nagios Libraries
      package:
        name:
          - gcc
          - glibc
          - glibc-common
          - perl
          - httpd
          - php
          - wget
          - gd
          - gd-devel
          - openssl-devel
          - make
          - gettext
          - automake
          - net-snmp
          - net-snmp-utils
          - python-pip
      when: ansible_distribution_major_version == '7'

    - name: Add nagios user
      user:
        name: nagios
        state: present

    - name: Add nagcmd group
      group:
        name: nagcmd
        state: present

    - name: Add nagios to nagcmd group
      user:
        name: nagios
        groups: nagcmd
        append: yes

    - name: Add apache to nagcmd group
      user:
        name: apache
        groups: nagcmd
        append: yes

    - name: Create Nagios directory PATH
      file:
        path: ~/nagios
        state: directory

    - name: Download Nagios
      get_url:
        url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        dest: ~/nagios/nagioscore.tar.gz
        mode: 0644

    - name: Extract Nagios
      unarchive:
        src: ~/nagios/nagioscore.tar.gz
        dest: ~/nagios
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Configure Nagios
      command: >
        ./configure --with-command-group=nagcmd
      args:
        chdir: ~/nagios/nagioscore

    - name: Compile and Install Nagios
      shell: |
        make all
        make install
        make install-init
        make install-commandmode
        make install-config
      args:
        chdir: ~/nagios/nagioscore

    - name: Install Nagios Web Configuration
      shell: make install-webconf
      args:
        chdir: ~/nagios/nagioscore

    - name: Set up Nagios admin password
      command: >
        htpasswd -s -c /usr/local/nagios/etc/htpasswd.users nagiosadmin
      ignore_errors: yes

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Download Nagios Plugins
      get_url:
        url: http://www.nagios-plugins.org/download/nagios-plugins-2.0.3.tar.gz
        dest: ~/nagios/nagios-plugins.tar.gz
        mode: 0644

    - name: Extract Nagios Plugins
      unarchive:
        src: ~/nagios/nagios-plugins.tar.gz
        dest: ~/nagios
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Configure and Install Nagios Plugins
      command: >
        ./configure --with-nagios-user=nagios --with-nagios-group=nagios
        make
        make install
      args:
        chdir: ~/nagios/nagios-plugins

    - name: Verify Nagios Configuration
      command: >
        /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg
      changed_when: false

    - name: Add Nagios service to startup
      systemd:
        name: nagios.service
        enabled: yes
      when: ansible_distribution_major_version == '7'

    - name: Start Nagios service
      service:
        name: nagios
        state: started
      when: ansible_distribution_major_version == '7'
