---
- name: Configure Cisco routers
  hosts: routers
  gather_facts: no
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: admin
    ansible_password: rdrgz
  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname {{ inventory_hostname }}

    - name: Set enable secret
      ios_config:
        lines:
          - enable secret rdrgz

    - name: Set console and vty passwords
      ios_config:
        lines:
          - line vty 0 4
          - password rdrgz
          - login

    - name: Set banner
      ios_config:
        lines:
          - banner motd # Unauthorized Access Denied #

    - name: Disable DNS lookup
      ios_config:
        lines:
          - no ip domain-lookup
