---
- hosts: R1
  gather_facts: no
  connection: local

  tasks:
    - name: OBTAIN LOGIN INFORMATION
      include_vars: secrets.yml

    - name: DEFINE PROVIDER
      set_fact:
        provider:
          host: "{{ ansible_host }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"

    - name: SET HOSTNAME
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
          - hostname R1

    - name: SET ENABLE SECRET
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
          - enable secret rdrgz

    - name: SET CONSOLE AND VTY PASSWORDS
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
          - line vty 0 4
          - password rdrgz
          - login

    - name: SET BANNER
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
          - banner motd # Unauthorized Access Denied #

    - name: DISABLE DNS LOOKUP
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        lines:
          - no ip domain-lookup

    - name: SAVE & BACKUP CONFIGURATION
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        save: yes
        backup: yes
