---
- name: Unblock IP address and allow ICMP traffic using iptables
  hosts: localhost
  become: yes
  tasks:
    - name: Unblock IP address using iptables
      command: iptables -D INPUT -s 192.168.56.104 -j DROP
      ignore_errors: yes

    - name: Allow ICMP traffic using iptables
      command: iptables -D INPUT -p icmp -j DROP
      ignore_errors: yes
