---
- name: Block IP address and ICMP traffic using iptables
  hosts: localhost
  become: yes
  tasks:
    - name: Block IP address using iptables
      command: iptables -A INPUT -s 192.168.56.104 -j DROP

    - name: Block ICMP traffic using iptables
      command: iptables -A INPUT -p icmp -j DROP
